### ISSUE TITLE
Error on ::File.size?(file_name)

### ISSUE THREAD

**Issue by kacosta** [rubyzip/rubyzip#311] opened 2016-12-22 18:16 UTC
I am getting this error

```
Errno::ENOENT: No such file or directory @ rb_file_s_size - C:/Users/k/Desktop/TestZip/archive1.zip
        from ../gems/rubyzip-1.1.6/lib/zip/file.rb:73:in `size'
        from ../gems/rubyzip-1.1.6/lib/zip/file.rb:73:in `size?'
        from ../gems/rubyzip-1.1.6/lib/zip/file.rb:73:in `initialize'
        from ../gems/rubyzip-1.1.6/lib/zip/file.rb:96:in `new'
        from ../gems/rubyzip-1.1.6/lib/zip/file.rb:96:in `open'
```

I get this error just when I deploy my app. On develop it works.
I was tracking the issue, and it fails on 

> **File:** rubyzip-1.1.6/lib/zip/file.rb
> **Function:** initialize
> **Line:** 73 ---> when !buffer && ::File.size?(file_name)

The error is on statement: ::File.size?(file_name)
When I tested it on console for file that doesn't exists it returns **nil**
But on production it fails

```
> File.size?(file_name)
Errno::ENOENT: No such file or directory @ rb_file_s_size - C:/Users/klins/Desktop/TestZip/archive1.zip
        from (irb):23:in `size'
        from (irb):23:in `size?'
        from (irb):23
```

Do you have any idea why? Is there a reason why use "size?" instead of "exist?" ?

Thanks!

**Comment by simonoff** [comment] 2017-03-07 15:11
It means that file must be exists and more then 0 bytes.

**Comment by hainesr** [comment] 2021-06-19 15:36
I cannot reproduce this at all. `::File.size?` is supposed to be safe and catch errors - including non-existent files. Maybe a bug in whatever version of ruby this was?

**Comment by hainesr** [comment] 2021-07-10 16:36
I'm going to close this as we can't reproduce it, and we have comprehensive tests that run on Windows now too. Please re-open or raise a new issue if this happens again for you. Thanks.

**Closed by hainesr** 2021-07-10 16:36 UTC
Labels: cannot reproduce, windows
