### ISSUE TITLE
undefined method `bytesize' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tycooon** [rubyzip/rubyzip#528] opened 2022-05-26 15:32 UTC
I get this error when trying to work with a correct Excel xlsx file:

```sh
>  ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

>  ruby test.rb
/Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:365:in `check_c_dir_entry_static_header_length': undefined method `bytesize' for nil:NilClass (NoMethodError)

      return if buf.bytesize == ::Zip::CDIR_ENTRY_STATIC_HEADER_LENGTH
                   ^^^^^^^^^
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:392:in `read_c_dir_entry'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:215:in `read_c_dir_entry'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:127:in `block in read_central_directory_entries'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:126:in `times'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:126:in `read_central_directory_entries'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:138:in `read_from_stream'
	from test.rb:5:in `<main>'
```

I created a small repo that can be used to reproduce the error. See https://github.com/tycooon/report-rubyzip-bug.

**Comment by Nakilon** [comment] 2022-05-29 08:39
I have no clue in this gem but I see that on Jun 18, 2021 there was a commit "Test that a corrupted cdir entry is caught." that fixes this but the tag 2.3.2 even though it was later, did not include the fix. I suppose until the newer gem version is released, you may try to specify to specify the commit hash in your Gemfile.

**Comment by tycooon** [comment] 2022-05-30 09:01
I tried to use version from master, but I get the following error:

```
/Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubyzip-ffa90a37cbb8/lib/zip/central_directory.rb:160:in `unpack_e_o_c_d': undefined method `positive?' for nil:NilClass (NoMethodError)

      @comment = if comment_length.positive?
                                  ^^^^^^^^^^
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubyzip-ffa90a37cbb8/lib/zip/central_directory.rb:240:in `read_eocds'
	from /Users/tycooon/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubyzip-ffa90a37cbb8/lib/zip/central_directory.rb:33:in `read_from_stream'
	from test.rb:5:in `<main>'
```

**Comment by hainesr** [comment] 2022-06-18 11:02
Hi @tycooon,

Thanks for raising this, and sorry it's taken so long for me to respond. Also, thank you for your detailed replication 🚀 

Firstly, I would caution that using `Zip::CentralDirectory` directly isn't really intended, and it's safer to use `Zip::File` instead. If you do use `Zip::File` with your example then all is good and it loads without error:

```ruby
require "zip"

stream = File.open("./example.xlsx")
zf = Zip::File.open(stream) #<Zip::File:0x000000010987e448 @name="example.xlsx", @create=false, @c...
```

The problem is that the stream needs to be in `binmode`, so for your example:

```ruby
require "zip"

stream = File.open("./example.xlsx", 'rb')
Zip::CentralDirectory.new.read_from_stream(stream)
```

I'll fix this so that we ensure `binmode` before reading the Central Directory. Thanks for spotting this.

I'll leave this issue open until I've pushed the fix.

**Closed** 2022-06-18 15:36 UTC
Labels: bug
