### ISSUE TITLE
File#open_buffer emits error when reading from a string

### ISSUE THREAD

**Issue by jurriaan** [rubyzip/rubyzip#199] opened 2014-12-06 11:31 UTC
I know this is not the way to read a file, but this is just for demonstration purposes:

``` ruby
Zip::File.open_buffer(open("some.xlsx").read) { |f| p f.entries.map(&:name) }
```

gives the following output:

``` ruby
["_rels/.rels", "xl/styles.xml", ..... ]
```

```
NoMethodError: undefined method `bytesize' for nil:NilClass
from .gem/ruby/2.1.5/gems/rubyzip-1.1.6/lib/zip/entry.rb:224:in `read_local_entry'
```

**Comment by TigerWolf** [comment] 2015-01-12 11:06
Im also getting this issue. Is there a work around for this?

**Comment by trappist** [comment] 2015-04-02 16:23
Duplicate of #177

**Comment by jdleesmiller** [comment] 2019-05-24 20:06
Closing as duplicate.

**Closed by jdleesmiller** 2019-05-24 20:06 UTC
