### ISSUE TITLE
Using Zip.sort_entries appears to change file header in place when using block with File.open

### ISSUE THREAD

**Issue by stadelmanma** [rubyzip/rubyzip#329] opened 2017-05-18 17:03 UTC
I ran into this when working with docx files and after refactoring some code the test fixtures were getting modified but for the life of me I couldn't tell how. The unzipped content of the archive is unchanged however the number of bytes slightly changes (which I assume is the file ordering?). `Zip::File.open.each` does not modify the file in place, nor does using `Zip::File.open_buffer` on the raw stream.

The block below can reproduce the error.
```ruby
Zip.sort_entries = true # required to process document.xml before numbering.xml
Zip::File.open('../fixtures/conditionals_template.docx') do |docx_zip|
end
```

For a full demonstration of the problem you can pull down my branch of Sablon [here](https://github.com/stadelmanma/sablon/tree/zip-modify-inplace) (use the zip-modify-inplace branch) and then run `bundle exec rake`. Ignore the failing test and afterwards you can use `git status` to see all of the fixtures be modified.

**Comment by leandronsp** [comment] 2017-05-19 16:06
@stadelmanma I realized the problem starts on `lib/zip/entry_set.rb:71`, exactly while calling `@entry_set.sort`. I suspect the root cause resides on the way the `@entry_set` is being manipulated thru.

**Comment by hainesr** [comment] 2021-06-29 13:42
It seems ridiculous that simply opening and closing a zip file with `Zip.sort_entries = true` should alter that file on disk.

**Closed** 2021-07-02 07:39 UTC
Labels: bug
